runtime: python310
service: kasapi
env: standard 
entrypoint: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker
instance_class: F2
handlers:
  # Matches requests to /images/... to files in static/images/...
  - url: /images
    static_dir: static/images
  
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: main.py
